# Generated by Django 4.0.4 on 2022-07-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='Nerdware_Files/')),
            ],
        ),
        migrations.AlterField(
            model_name='position',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Position_Files/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Project_Files/%Y/%m/%D/'),
        ),
    ]
